import RootLayoutClient from "./RootLayoutClient";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Wrap children in Client Layout for hooks
  return <RootLayoutClient>{children}</RootLayoutClient>;
}
